### ISSUE TITLE
Manually set min/max values of dataset

### ISSUE THREAD

**Issue by scompt** [robinhoodmarkets/spark#2]
Cool library! Thanks for releasing it.

**What I'd like to do**

I'd like to overlay a bunch of SparkViews. So far, it works and looks basically how I want it to. The problem is that the scale of the different SparkViews is different because the range of the data for each chart is different. If there was were methods in SparkAdapter that allowed me to specify the full range of the whole dataset, the scale of the individual SparkViews would be the same and everything would look as expected.

**How I'd like to do it**

I thought about adding `getMax()` and `getMin()` methods to `SparkAdapter`. They could also be protected behind a `hasManualMinMax()` method similar to `hasBaseline()`. The manually set min and max would then be used by `ScaleHelper`.

What do you think?

**Comment by danh32** [comment]
Sounds reasonable! Maybe we could avoid `hasManualMinMax()` by having default implementations of `getMin()` and `getMax()` that can be overridden for the manual case. I'll want to take a closer look first, though.

**Comment by scompt** [comment]
I thought about that as well, but since min and max are floats, I thought it might be weird finding a sentinel value. I guess it could be Float.MAX_VALUE.

**Comment by danh32** [comment]
I think it could be that the default `getMin()` loops over the data and returns the actual min value. Then you could override and supply your own value if you wanted. I'll take a look soon!

**Comment by danh32** [comment]
@scompt the api is a bit different than you described. We've added a method to SparkAdapter, `public RectF getDataBounds()`, that you can override to return alternate min/max values for X and Y. I ran a quick local test with two overlapped `SparkView`s and everything seemed right. Let us know if you hit any issues.

I'd like to wait just a bit longer before doing another release in case anything pops up. In the meantime, you can bundle the code locally to get the latest. I've also heard of Jitpack (https://jitpack.io/) being used for this, but I've never used it personally.

**Comment by scompt** [comment]
I'll try it soon. Thanks for the quick implementation. 👍
